version: "3.8"

services:
  api:
    build: .
    container_name: wtm-api
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - air-bin:/app/tmp
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: wtm-db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data  

volumes:
  pgdata:
  air-bin:
